git:
  depth: 5
stages:
- Build and Test
- Package
jobs:
  include:
  - stage: Build and Test
    language: java
    jdk: oraclejdk11
    before_script:
    - cd sample-application-backend
    script:
    - echo "Maven build"
    - mvn clean verify org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=matthieu-bd_sample-application-students
    - echo "Run test coverage and Quality Gate"
    
  - stage: Build and Test
    language: node.js
    node_js: '12.20'
    before_script:
    - cd sample-application-frontend
    script:
    - echo "NPM install and build"
    - npm install
    - npm run lint
    - npm run test
    
    
  - stage: Package
    before_script:
    - cd sample-application-backend
    script:
    - echo "Docker build ..."
    - docker build -t matthieured/app-backend .
    - echo "Docker login ..."
    - echo "$dockerpassword" | docker login -u "$dockerid" --password-stdin
    - echo "Docker push ..."
    - docker push matthieured/app-backend
    
  - stage: Package
    before_script:
    - cd sample-application-frontend
    script:
    - echo "Docker build ..."
    - docker build -t matthieured/app-frontend .
    - echo "Docker login ... $dockerid"
    - echo "$dockerpassword" | docker login -u "$dockerid" --password-stdin
    - echo "Docker push ..."
    - docker push matthieured/app-frontend

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.npm"
services:
- docker

addons:
  sonarcloud:
    organization: "matthieu-bd"
    token: "$SONARCLOUD_TOKEN"